### ISSUE TITLE
起動手順がREADMEにあると助かります。

### ISSUE THREAD

**Issue by EikiObara** [rask-kasuterra/guild_masters#1]
こんな感じでどうでしょうか。一応mdで書いてるのでそのまま貼り付ければ行けるかも。

--------------------------------------------

## ローカル環境起動手順

1. ビルドする

   `make build-dev`

2. サーバーに入ってマイグレーションする

   `make exec-dev`

   サーバ内

   ```
   python manage.py migrate
   exit
   ```

3. サーバーを立ち上げる

   `make run-server`

4. ブラウザで見る

   `http://localhost:8001/ise_guil_calc/`

**Comment by EikiObara** [comment]
プルリクを出しました。
https://github.com/rask-kasuterra/guild_masters/pull/2

**Comment by rask-kasuterra** [comment]
プルリクマージ完了
